### ISSUE TITLE
Requesting Multiple Users does not return seed for each individual

### ISSUE THREAD

**Issue by rinatio** [RandomAPI/Randomuser.me-Data#26]
It would be useful to have a `seed` for each individual user in the list, so we could reference to the same user later. Now it includes the `seed` only in the first record and it seems to be a `seed` for the multiple users request itself

**Comment by keitharm** [comment]
Due to the nature of how the API generates multiple users, this is currently not possible.

In the past, every user having a seed in the results was actually a bug and only the 1st result would be a valid seed associated with that 1st user. All the other seeds were random and didn't actually return the correct results.

The current version only includes a seed in the 1st result to prevent confusion. So yes, the seed's purpose currently is to regenerate a "set" of random users.

There are plans in the future to convert our codebase from PHP to Node.js and recode the API engine so that features like this can be implemented...but for now, it isn't feasible to add this functionality.
